services:
  stickerget:
    restart: always
    container_name: stickerget
    image: megasuite/tg_sticker_get:0.2
    volumes:
      - ./config/config.yaml:/app/config.yaml
    depends_on:
      - redis

  redis:
  	restart: always
    image: redis:alpine
    container_name: redis